name: promed
description: A new Flutter project.

publish_to: 'none'

version: 0.4.0+1

environment:
  sdk: ">=2.18.5 <3.2.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  http: ^1.1.0
  auto_size_text: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_secure_storage: ^8.0.0
  video_player: ^2.2.0
  chewie: ^1.1.0
  flutter_windowmanager: ^0.2.0
  flutter_launcher_icons: ^0.13.1
  better_player: ^0.0.73
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.0.10
  share_plus: ^6.3.4
  flutter_widget_from_html: ^0.8.5
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.3.2
  firebase_messaging: ^14.6.6
  overlay_support: ^2.1.0
  firebase_core: ^2.15.1
  provider: ^6.0.5
  mask_text_input_formatter: ^2.5.0
  camera: ^0.10.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "assets/images/ProMed.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/Logo.jpg
    - assets/images/forgotpasswordicon.jpg
    - assets/images/subjectIcon.jpg
    - assets/images/videoIcon.png
    - assets/images/default-profile-pic.png
    - assets/images/email_verification.png
    - assets/images/lock0.png
    - assets/images/lock1.png
    - assets/images/TeacherMalek.JPG
    - assets/images/default-profile-pic.jpeg
    - assets/images/TeacherShadi.jpg
